# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc0b0153e144ec0f8172b2d8557bc45a9fee0ebaafe8d500073e46cffd0180be7ae80123f3bdb7b413404acaf6f1e82d42b4cef8272a03c3035a47b0c5f252c0

test:
  secret_key_base: 7ab7b2bb4dad63e8b095875085372ea24fe581c1cb8649cfda48fd03ebf366612b09152c7270083ba95fe40df0b7eedaf3b54344c3af67e223e975659f9a88d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
